version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs-events
    restart: unless-stopped
    env_file: .env
    environment:
      - JWT_KEY=JWT_KEY
      - SESSIONS_SECRET=$SESSIONS_SECRET
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '81:3000'
    depends_on:
      - db
    volumes:
      - '.:/home/node/app'
      - 'node_modules:/home/node/app/node_modules'
    networks:
      - events-network
  db:
    image: 'mongo:4.1.8-xenial'
    container_name: db_events
    env_file: .env
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - './data/db:/data/db'
    networks:
      - events-network
networks:
  events-network:
    driver: bridge
volumes:
  node_modules: null
